
<footer class="footer main-footer">
    <div class="footer__inner main-width">
        <div class="main-footer__link-wrap col-1-gut-1">
            <a class="link-logo link-logo_white link-logo_main" href="/"></a>
        </div>
        <div class="col-2-gut-1 form-wrap">
            <form class="form-search" action="/search">
                <div class="form-search__inner">
                    <input class="input-text form-search__input" type="text" name="q" placeholder="Поиск"/>
                </div>
            </form>
            <a class="footer-link" href="/serial/list">Список сериалов</a>
        </div>
        <a href="#login" class="button button--login">Вход</a>
        <div class="col-1-gut-0 social">
            <a class="social__link social__link-fb" target="_blank" href="#"></a>
            <a class="social__link social__link-vk" target="_blank" href="https://vk.com/tvzim"></a>
            <a class="social__link social__link-in" target="_blank" href="#"></a>
        </div>
    </div>
</footer>
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter40091825 = new Ya.Metrika({ id:40091825, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/40091825" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<script src="/build/js/production.min.js?v=<?=filemtime ($this->config->application->baseDir.'/../../public/build/js/production.min.js');?>"></script>
</body>
</html>