<!DOCTYPE html>
<html>
<head>
    <?php echo $this->tag->getTitle(); ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />

    <meta name="google-site-verification" content="XjWBQKTYBlkbjwC2K9DblW3MHABzd9d4-twwo17bn9s" />
    <meta name="yandex-verification" content="4ec2743af887b20a" />

    <link rel="apple-touch-icon" sizes="57x57" href="/icon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/icon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/icon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/icon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/icon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/icon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/icon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/icon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/icon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/icon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/icon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icon/favicon-16x16.png">
    <link rel="manifest" href="/icon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/icon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="translucent-black" />
    <meta name="apple-mobile-web-app-title" content="TVZ" />

    <meta property="og:title" content="<?=$this->CTags->getPageTitle();?>" />
    <meta property="og:site_name" content="<?=$this->CTags->getPageTitle();?>"/>
    <meta property="og:url" content="https://tvz.im<?=$this->router->getRewriteUri();?>" />

    <?php echo $this->CTags->getImage(); ?>
    <?php echo $this->CTags->getDescription(); ?>

    <link rel="stylesheet" href="/build/css/production.min.css?v=<?=filemtime ($this->config->application->baseDir.'/../../public/build/css/production.min.css');?>"/>
    <?php //var_dump($this->config->application->baseDir);?>
</head>
<body>