<header class="header header-main main-width">
    <div class="header-main__link-wrap col-1-gut-1">
        <a class="link-logo link-logo_red link-logo_main" href="/"></a>
    </div>
    <form class="form-search col-2-gut-1" action="/search">
        <div class="form-search__inner">
            <input class="input-text form-search__input" type="text" name="q" placeholder="Поиск"/>
        </div>
    </form>
    <a href="/serial/list" class="link link--header">Список сериалов</a>
    <a href="#login" class="button button--login">Вход</a>
</header>